# Generated by Django 5.2 on 2026-07-26 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_department_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subject', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('current_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_files', to='mainapp.employee')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_files', to='mainapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FileMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('FORWARD', 'Forward'), ('RETURN', 'Return'), ('CLOSE', 'Close')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='mainapp.file')),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_files', to='mainapp.employee')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_files', to='mainapp.employee')),
            ],
            options={
                'ordering': ['moved_at'],
            },
        ),
    ]
