# Generated by Django 5.2 on 2026-07-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_file_filemovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
