# Generated by Django 5.2 on 2026-07-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_file_file_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
